# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170521_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
